# Generated by Django 5.2.5 on 2025-08-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='Глобальный доступ ко всем урокам'),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.videolesson', verbose_name='Урок'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
