# Generated by Django 5.2.5 on 2025-08-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_useraccess_is_global_alter_useraccess_lesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccess',
            name='is_global',
        ),
        migrations.AddField(
            model_name='useraccess',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Допущен к видео'),
        ),
    ]
